window.MediaNestData = [
  {
    id: "big-buck-bunny",
    title: "Big Buck Bunny",
    kind: "Pelicula abierta",
    meta: "2008 | 10 min | Familiar",
    section: "movies",
    year: "2008",
    durationText: "10 min",
    rating: "TV-PG",
    genres: "Animacion, Comedia",
    description: "Un conejo tranquilo decide defenderse cuando tres pequenos animales convierten su hogar en un campo de travesuras.",
    image: "https://archive.org/services/img/BigBuckBunny_328",
    backdrop: "https://archive.org/services/img/BigBuckBunny_328",
    progress: 0,
    mediaType: "video",
    source: "https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4"
  },
  {
    id: "sintel-movie",
    title: "Sintel",
    kind: "Cortometraje abierto",
    meta: "2010 | 15 min | Fantasia",
    section: "movies",
    year: "2010",
    durationText: "15 min",
    rating: "TV-14",
    genres: "Fantasia, Aventura",
    description: "Una joven guerrera atraviesa un mundo hostil para encontrar al dragon que salvo cuando era pequeno.",
    image: "https://archive.org/services/img/VODO138Sintel",
    backdrop: "https://archive.org/services/img/VODO138Sintel",
    progress: 0,
    mediaType: "video",
    source: "https://archive.org/download/VODO138Sintel/Sintel.2010.Theora-VODO.mp4"
  },
  {
    id: "tears-of-steel-movie",
    title: "Tears of Steel",
    kind: "Cortometraje abierto",
    meta: "2012 | 12 min | Ciencia ficcion",
    section: "movies",
    year: "2012",
    durationText: "12 min",
    rating: "TV-14",
    genres: "Ciencia ficcion, Accion",
    description: "Un grupo de combatientes intenta corregir un error del pasado antes de que una invasion mecanica destruya Amsterdam.",
    image: "https://archive.org/services/img/TearsOfSteel_esp",
    backdrop: "https://archive.org/services/img/TearsOfSteel_esp",
    progress: 0,
    mediaType: "video",
    source: "https://archive.org/download/TearsOfSteel_esp/Tears_of_steel.mp4"
  },
  {
    id: "elephants-dream-movie",
    title: "Elephants Dream",
    kind: "Pelicula abierta",
    meta: "2006 | 11 min | Experimental",
    section: "movies",
    year: "2006",
    durationText: "11 min",
    rating: "TV-PG",
    genres: "Animacion, Fantasia",
    description: "Dos viajeros recorren el interior de una maquina gigantesca mientras sus distintas formas de ver el mundo chocan.",
    image: "https://archive.org/services/img/elephants-dream_202601",
    backdrop: "https://archive.org/services/img/elephants-dream_202601",
    progress: 0,
    mediaType: "video",
    source: "https://archive.org/download/elephants-dream_202601/Elephants%20Dream.mp4"
  },
  {
    id: "open-worlds",
    title: "Mundos abiertos",
    kind: "Serie de prueba",
    meta: "1 temporada | 3 episodios",
    section: "series",
    year: "2026",
    durationText: "3 episodios",
    rating: "TV-14",
    genres: "Antologia, Fantasia",
    description: "Una antologia de cortometrajes abiertos que explora mundos fantasticos, futuros posibles y decisiones inesperadas.",
    image: "https://archive.org/services/img/VODO138Sintel",
    backdrop: "https://archive.org/services/img/TearsOfSteel_esp",
    progress: 0,
    mediaType: "video",
    source: "",
    episodes: [
      { id: "open-worlds-e1", title: "1. Sintel", durationText: "15 min", description: "Una guerrera sigue el rastro de un dragon perdido.", image: "https://archive.org/services/img/VODO138Sintel", source: "https://archive.org/download/VODO138Sintel/Sintel.2010.Theora-VODO.mp4" },
      { id: "open-worlds-e2", title: "2. Tears of Steel", durationText: "12 min", description: "El futuro de una ciudad depende de corregir una vieja decision.", image: "https://archive.org/services/img/TearsOfSteel_esp", source: "https://archive.org/download/TearsOfSteel_esp/Tears_of_steel.mp4" },
      { id: "open-worlds-e3", title: "3. Elephants Dream", durationText: "11 min", description: "Dos viajeros se internan en una maquina imposible.", image: "https://archive.org/services/img/elephants-dream_202601", source: "https://archive.org/download/elephants-dream_202601/Elephants%20Dream.mp4" }
    ]
  },
  {
    id: "animation-lab",
    title: "Laboratorio animado",
    kind: "Serie de prueba",
    meta: "1 temporada | 3 episodios",
    section: "series",
    year: "2026",
    durationText: "3 episodios",
    rating: "TV-PG",
    genres: "Animacion, Familiar",
    description: "Una seleccion ligera de animaciones y demostraciones abiertas preparada para probar el reproductor de MediaNest.",
    image: "https://archive.org/services/img/BigBuckBunny_328",
    backdrop: "https://archive.org/services/img/BigBuckBunny_328",
    progress: 0,
    mediaType: "video",
    source: "",
    episodes: [
      { id: "animation-lab-e1", title: "1. Big Buck Bunny", durationText: "10 min", description: "Una comedia animada en un bosque lleno de problemas.", image: "https://archive.org/services/img/BigBuckBunny_328", source: "https://archive.org/download/BigBuckBunny_328/BigBuckBunny_512kb.mp4" },
      { id: "animation-lab-e2", title: "2. Flower", durationText: "30 s", description: "Una breve prueba visual en alta definicion.", image: "https://archive.org/services/img/flower_202302", source: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" },
      { id: "animation-lab-e3", title: "3. Flower", durationText: "30 s", description: "Una pieza corta para comprobar carga y continuidad.", image: "https://archive.org/services/img/flower_202302", source: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" }
    ]
  },
  {
    id: "trex",
    title: "T-Rex Roar",
    kind: "Audio",
    meta: "Clip sonoro de prueba",
    section: "music",
    progress: 12,
    mediaType: "audio",
    source: "https://interactive-examples.mdn.mozilla.net/media/cc0-audio/t-rex-roar.mp3"
  }
];
